name: "Close stale issues"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - .github/workflows/stale.yml

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has not
            had recent activity. It will be closed if no further activity
            occurs. The main purpose of this is to keep the issue tracker
            focused to what is actively being worked on, so that the amount and
            variety of open yet inactive issues does not overwhelm contributors.



            An issue closed as stale is not rejected â€” further discussion is
            welcome in its closed state, and it can be resurrected at any time.
            odoc maintainers regularly check issues that were closed as stale in
            the past, to see if the time is right to reopen and work on them
            again. PRs addressing issues closed as stale are as welcome as PRs
            for open issues. They will be given the same review attention, and
            any other help.
          days-before-stale: 365
          days-before-close: -1
          exempt-issue-labels: "bug,not stale"
          stale-issue-label: "stale"
